In [2]:
import numpy as np

MELHORIA 1:

1. Se o elemento abaixo do pivô for zero, continue.
2. Se um dos pivôs for zero, mostrar uma mensagem de erro.

In [4]:
# Dado um sistema S, representado por uma matriz A de ordem N e por uma matriz resultado B de ordem Nx1, o algoritmo
# abaixo pega essas matrizes e retorna a matriz triangular equivalente a A e sua matriz resultado correspondente

# Aplicando a etapa 1

def escalonamento1(a,b,n):
    for k in range(n-1):
        for i in range(k+1,n):
            if a[i,k] == 0:
                print("A iteração ", k+1, " foi pulada")
                continue
            
            if a[i,k] == 0:
                print("Do contrário, esta mensagem seria exibida")
            
            m = a[i,k]/a[k,k]
            a[i,k] = 0
            
            for j in range(k+1,n):
                a[i,j] = a[i,j] - m*a[k,j]
            
            b[i,0] = b[i,0] - m*b[k,0]

In [5]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9
# 2*x1 + 1*x2 - 1*x3 =  3 ==> 2*x1 será substituído por 0*x1
# 3*x1 - 1*x2 - 2*x3 = -4

A = np.matrix([[1,2,1],[0,1,-1],[3,-1,-2]])
B = np.matrix([[9],[3],[-4]])

escalonamento1(A,B,3)
print("\n", A)
print("\n", B)

A iteração  1  foi pulada

 [[  1   2   1]
 [  0   1  -1]
 [  0   0 -12]]

 [[  9]
 [  3]
 [-10]]


In [7]:
# Dado um sistema S, representado por uma matriz A de ordem N e por uma matriz resultado B de ordem Nx1, o algoritmo
# abaixo pega essas matrizes e retorna a matriz triangular equivalente a A e sua matriz resultado correspondente

# Aplicando a etapa 2

def escalonamento2(a,b,n):
    for k in range(n-1):
        if a[k,k] == 0:
            print("Pivô = 0: Nenhuma operação será executada")
            break
        
        for i in range(k+1,n):
            if a[i,k] == 0:
                print("A iteração ", k+1, " foi pulada")
                continue
            
            if a[i,k] == 0:
                print("Do contrário, esta mensagem seria exibida")
            
            m = a[i,k]/a[k,k]
            a[i,k] = 0
            
            for j in range(k+1,n):
                a[i,j] = a[i,j] - m*a[k,j]
            
            b[i,0] = b[i,0] - m*b[k,0]

In [8]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9 ==> 1*x1 será substituído por 0*x1
# 2*x1 + 1*x2 - 1*x3 =  3
# 3*x1 - 1*x2 - 2*x3 = -4

C = np.matrix([[0,2,1],[2,1,-1],[3,-1,-2]])
D = np.matrix([[9],[3],[-4]])

escalonamento2(C,D,3)
print("\n", C)
print("\n", D)

Pivô = 0: Nenhuma operação será executada

 [[ 0  2  1]
 [ 2  1 -1]
 [ 3 -1 -2]]

 [[ 9]
 [ 3]
 [-4]]


MELHORIA 2:
    
    1 . Se o determinante for igual a 0, exibir uma mensagem de erro
    2 . Senão, executar a Gauus Elimination

In [9]:
# Dado um sistema S, representado por uma matriz A de ordem N e por uma matriz resultado B de ordem Nx1, o algoritmo
# abaixo pega essas matrizes e retorna a matriz triangular equivalente a A e sua matriz resultado correspondente

# Aplicando a Melhoria 2

def escalonamento3(a,b,n):
    for i in range(n):
        if a[i,i] != 0: 
            continuar = 'true'
        else:
            continuar = 'false'
            break
    
    if continuar == 'true':
        escalonamento2(a,b,n)
    else:
        print("Determinante igual a 0: Nenhuma operação executada")

In [11]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9
# 2*x1 + 1*x2 - 1*x3 =  3 ==> 1*x2 serão substituído por 0*x2
# 3*x1 - 1*x2 - 2*x3 = -4

E = np.matrix([[1,2,1],[2,0,-1],[3,-1,-2]])
F = np.matrix([[9],[3],[-4]])

escalonamento3(E,F,3)

print("\n", E)
print("\n", F)

Determinante igual a 0: Nenhuma operação executada

 [[ 1  2  1]
 [ 2  0 -1]
 [ 3 -1 -2]]

 [[ 9]
 [ 3]
 [-4]]


PIVOTEAMENTO PARCIAL: CONTAR O NÚMERO DE TROCAS DE LINHA FEITOS NUMA MATRIZ

In [16]:
# Pega duas matrizes a e b, de ordem n e nx1, respectivamente, e retorna um única matriz x com os elementos de a e b

def concatenacaoDeMatrizes(a,b):
    x = np.zeros((a.shape[0], a.shape[1]+1))
    x[:,:-1] = a
    x[:,-1:] = b
    return x

In [15]:
# Pega uma matriz x, de n linhas e n+1 colunas, e a divide em duas matrizes menores a e b, de ordem n e nx1,
# respectivamente

def separacaoDeMatrizes(a,b,x):
    for i in range(a.shape[0]):
        for j in range(a.shape[0]):
            a[i,j] = x[i,j]
        b[i,0] = x[i,-1]

In [17]:
# Pega uma matriz x, de n linhas e n+1 colunas, e a divide em duas matrizes menores a e b, de ordem n e nx1 respect.

def separacaoDeMatrizes(a,b,x):
    for i in range(a.shape[0]):
        for j in range(a.shape[0]):
            a[i,j] = x[i,j]
        b[i,0] = x[i,-1]

In [18]:
# Inverte a posição de duas linhas de uma matriz x

def trocaDeLinha(x,i,k,indexMax):
    iChange = indexMax + i
    aux = np.copy(x[k,:])
    x[k,:] = np.copy(x[iChange,:])
    x[iChange,:] = np.copy(aux)

In [25]:
# Concatena duas matrizes a e b, cria uma matriz coluna com os elementos abaixo do pivô x[k,k] e efetua a troca de
# posição entre a linha do pivô e a linha que contém o maior elemento na mesma coluna

def pivoteamento(a,b,k,i):
    x = concatenacaoDeMatrizes(a,b) # união das matrizes a e b numa única matriz x
    n = np.shape(x)[0] - 1          # último index de x
    col = x[i:n+1,k]                # matriz coluna com os elementos abaixo do pivô
    colAbs = np.abs(col)            # matriz de valores absolutos da matriz coluna
    indexMax = np.argmax(colAbs)    # index do valor máximo da matriz de números absolutos
    trocaDeLinha(x,i,k,indexMax)    # efetua a troca entre a linha do pivô e a linha do elemento máximo
    separacaoDeMatrizes(a,b,x)      # efetua a separação de x nas matrizes a e b originais
    return 1                        # retorna que uma operação de troca de linha foi feita

In [28]:
# Dada uma matriz de coeficientes A e uma matriz de resultados B, efetua as trocas de linha necessárias para que o
# escalonamento seja feito corretamente e retorna o número de trocas feitas até a conclusão do processo

def escalonamentoComPivoteamento(a,b):
    t = 0
    for k in range(a.shape[0]-1):
        for i in range(k+1,a.shape[0]):
            t = t + pivoteamento(a,b,k,i)
            m = a[i,k]/a[k,k]
            a[i,k] = 0
            
            for j in range(k+1,a.shape[0]):
                a[i,j] = a[i,j] - m*a[k,j]
            
            b[i,0] = b[i,0] - m*b[k,0]
    return t

In [30]:
# Dado um sistema S, representado por uma matriz A uma matriz resultado B, o algoritmo abaixo pega uma matriz triangular
# equivalente e sua matriz resultado correspondente e calcula a solução de S

def solucao(a,b):
    n = a.shape[0]
    x = np.zeros((n,1)) # Cria uma matriz x[n,1] para receber a solução
    x[n-1,0] = b[n-1,0]/a[n-1,n-1]
    
    for k in range(n-1,-1,-1):
        s = 0
        for j in range(k+1,n):
            s = s + a[k,j]*x[j,0]
            x[k,0] = (b[k,0] - s)/a[k,k]
    
    return x

In [32]:
# Solução sem pivoteamento:

# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9
# 2*x1 + 1*x2 - 1*x3 =  3
# 3*x1 - 1*x2 - 2*x3 = -4

G = np.matrix([[1.,2.,1.],[2.,1.,-1.],[3.,-1.,-2.]])
H = np.matrix([[9.],[3.],[-4.]])
I = concatenacaoDeMatrizes(G,H)
escalonamento3(G,H,3)
S = solucao(G,H)

print("\nMatriz concatenada:\n\n", I)
print("\nMatriz de coeficientes escalonada:\n\n", G)
print("\nMatriz de resultados escalonada: \n\n", H)
print("\nSolução:\n\n", S)


Matriz concatenada:

 [[ 1.  2.  1.  9.]
 [ 2.  1. -1.  3.]
 [ 3. -1. -2. -4.]]

Matriz de coeficientes escalonada:

 [[ 1.  2.  1.]
 [ 0. -3. -3.]
 [ 0.  0.  2.]]

Matriz de resultados escalonada: 

 [[  9.]
 [-15.]
 [  4.]]

Solução:

 [[ 1.]
 [ 3.]
 [ 2.]]


In [36]:
# Solução com pivoteamento:

# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9
# 2*x1 + 1*x2 - 1*x3 =  3
# 3*x1 - 1*x2 - 2*x3 = -4

J = np.matrix([[1.,2.,1.],[2.,1.,-1.],[3.,-1.,-2.]])
K = np.matrix([[9.],[3.],[-4.]])
L = concatenacaoDeMatrizes(J,K)
trocasDeLinha = escalonamentoComPivoteamento(J,K)
T = solucao(J,K)

print("\nMatriz concatenada:\n\n", L)
print("\nMatriz de coeficientes escalonada (compivoteamento):\n\n", J)
print("\nMatriz de resultados escalonada (com pivoteamento): \n\n", K)
print("\nNumero de trocas de linha: ", trocasDeLinha)
print("\nSolução:\n\n", T)


Matriz concatenada:

 [[ 1.  2.  1.  9.]
 [ 2.  1. -1.  3.]
 [ 3. -1. -2. -4.]]

Matriz de coeficientes escalonada (compivoteamento):

 [[ 1.          2.          1.        ]
 [ 0.         -7.         -5.        ]
 [ 0.          0.         -0.85714286]]

Matriz de resultados escalonada (com pivoteamento): 

 [[  9.        ]
 [-31.        ]
 [ -1.71428571]]

Numero de trocas de linha:  3

Solução:

 [[ 1.]
 [ 3.]
 [ 2.]]
