In [6]:
import numpy as np

MELHORIA 1:

1. Se o elemento abaixo do pivô for zero, continue.
2. Se um dos pivôs for zero, mostrar uma mensagem de erro.

In [16]:
# Dado um sistema S, representado por uma matriz A de ordem N e por uma matriz resultado B de ordem Nx1, o algoritmo
# abaixo pega essas matrizes e retorna a matriz triangular equivalente a A e sua matriz resultado correspondente

# Aplicando a etapa 1

def escalonamento1(a,b,n):
    for k in range(n-1):
        for i in range(k+1,n):
            if a[i,k] == 0:
                print("A iteração ", k+1, " foi pulada")
                continue
            
            if a[i,k] == 0:
                print("Do contrário, esta mensagem seria exibida")
            
            m = a[i,k]/a[k,k]
            a[i,k] = 0
            
            for j in range(k+1,n):
                a[i,j] = a[i,j] - m*a[k,j]
            
            b[i,0] = b[i,0] - m*b[k,0]

In [18]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9
# 2*x1 + 1*x2 - 1*x3 =  3 ==> 2*x1 será substituído por 0*x1
# 3*x1 - 1*x2 - 2*x3 = -4

A = np.matrix([[1,2,1],[0,1,-1],[3,-1,-2]])
B = np.matrix([[9],[3],[-4]])

escalonamento1(A,B,3)
print("\n", A)
print("\n", B)

A iteração  1  foi pulada

 [[  1   2   1]
 [  0   1  -1]
 [  0   0 -12]]

 [[  9]
 [  3]
 [-10]]


In [19]:
# Dado um sistema S, representado por uma matriz A de ordem N e por uma matriz resultado B de ordem Nx1, o algoritmo
# abaixo pega essas matrizes e retorna a matriz triangular equivalente a A e sua matriz resultado correspondente

# Aplicando a etapa 2

def escalonamento2(a,b,n):
    for k in range(n-1):
        if a[k,k] == 0:
            print("Pivô = 0: Nenhuma operação será executada")
            break
        
        for i in range(k+1,n):
            if a[i,k] == 0:
                print("A iteração ", k+1, " foi pulada")
                continue
            
            if a[i,k] == 0:
                print("Do contrário, esta mensagem seria exibida")
            
            m = a[i,k]/a[k,k]
            a[i,k] = 0
            
            for j in range(k+1,n):
                a[i,j] = a[i,j] - m*a[k,j]
            
            b[i,0] = b[i,0] - m*b[k,0]

In [20]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9 ==> 1*x1 será substituído por 0*x1
# 2*x1 + 1*x2 - 1*x3 =  3
# 3*x1 - 1*x2 - 2*x3 = -4

C = np.matrix([[0,2,1],[2,1,-1],[3,-1,-2]])
D = np.matrix([[9],[3],[-4]])

escalonamento2(C,D,3)
print("\n", C)
print("\n", D)

Pivô = 0: Nenhuma operação será executada

 [[ 0  2  1]
 [ 2  1 -1]
 [ 3 -1 -2]]

 [[ 9]
 [ 3]
 [-4]]


MELHORIA 2:
    
    1 . Se o determinante for igual a 0, exibir uma mensagem de erro
    2 . Senão, executar a Gauus Elimination

In [30]:
# Dado um sistema S, representado por uma matriz A de ordem N e por uma matriz resultado B de ordem Nx1, o algoritmo
# abaixo pega essas matrizes e retorna a matriz triangular equivalente a A e sua matriz resultado correspondente

# Aplicando a Melhoria 2

def escalonamento3(a,b,n):
    for i in range(n):
        if a[i,i] != 0: 
            continuar = 'true'
        else:
            continuar = 'false'
            break
    
    if continuar == 'true':
        escalonamento2(a,b,n)
    else:
        print("Determinante igual a 0: Nenhuma operação executada")

In [31]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9
# 2*x1 + 1*x2 - 1*x3 =  3 ==> 1*x2 serão substituído por 0*x2
# 3*x1 - 1*x2 - 2*x3 = -4

E = np.matrix([[1,2,1],[2,0,-1],[3,-1,-2]])
F = np.matrix([[9],[3],[-4]])

escalonamento3(E,F,3)

print("\n", E)
print("\n", F)

Determinante igual a 0: Nenhuma operação executada

 [[ 1  2  1]
 [ 2  0 -1]
 [ 3 -1 -2]]

 [[ 9]
 [ 3]
 [-4]]
