In [4]:
import numpy as np

ALGORITMO I: RESOLUÇÃO DE UM SISTEMA LINEAR TRIANGULAR SUPERIOR

In [109]:
# Dado um sistema S, representado por uma matriz M de ordem N, o algoritmo abaixo pega uma matriz triangular equivalente
# e a matriz resultado e calcula a solução de S

def solucao(a,b,n):
    x = np.zeros((n,1)) # Cria uma matriz x[n,1] para receber a solução
    x[n-1,0] = b[n-1,0]/a[n-1,n-1]
    
    for k in range(n-1,-1,-1):
        s = 0
        for j in range(k+1,n):
            s = s + a[k,j]*x[j,0]
            x[k,0] = (b[k,0] - s)/a[k,k]
    
    return x

In [111]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9
# 2*x1 + 1*x2 - 1*x3 =  3
# 3*x1 - 1*x2 - 2*x3 = -4

# Sistema escalonado:
#
# 1*x1 + 2*x2 + 1*x3 =    9
#      - 3*x2 - 3*x3 =  -15
#               2*x3 =  4

M = np.matrix([[1,2,1],[0,-3,-3],[0,0,2]])
R = np.matrix([[9],[-15],[4]])
X = solucao(M,R,3)
print(X)

[[ 1.]
 [ 3.]
 [ 2.]]


ALGORITMO II: RESOLUÇÃO DE Ax = B ATRAVÉS DO MÉTODO DA ELIMINAÇÃO DE GAUSS

In [104]:
# Dado um sistema S, representado por uma matriz M de ordem N e por uma matriz resultado R de ordem Nx1, o algoritmo
# abaixo pega essas matrizes e retorna a matriz triangular equivalente a M e sua matriz resultado correspondente

def escalonamento(a,b,n):
    for k in range(n-1):
        for i in range(k+1,n):
            m = a[i,k]/a[k,k]
            a[i,k] = 0
            for j in range(k+1,n):
                a[i,j] = a[i,j] - m*a[k,j]
            b[i,0] = b[i,0] - m*b[k,0]

In [112]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9
# 2*x1 + 1*x2 - 1*x3 =  3
# 3*x1 - 1*x2 - 2*x3 = -4

O = np.matrix([[1,2,1],[2,1,-1],[3,-1,-2]])
P = np.matrix([[9],[3],[-4]])

escalonamento(O,P,3)
print("\n", O)
print("\n", P)


 [[ 1  2  1]
 [ 0 -3 -3]
 [ 0  0  2]]

 [[  9]
 [-15]
 [  4]]


In [113]:
# Determina o resultado

X = solucao(O,P,3)
print("\n", X)


 [[ 1.]
 [ 3.]
 [ 2.]]
