In [1]:
import numpy as np

ALGORITMO I: RESOLUÇÃO DE UM SISTEMA LINEAR TRIANGULAR SUPERIOR

In [3]:
# Dado um sistema S, representado por uma matriz M de ordem N, o algoritmo abaixo pega uma matriz triangular equivalente
# e a matriz resultado e calcula a solução de S

def solucao(m,r,n):
    x = np.zeros((n,1)) # Cria uma matriz x[n,1] para receber a solução
    x[n-1,0] = r[n-1,0]/m[n-1,n-1]
    
    for i in range(n-1,-1,-1):
        s = 0
        for j in range(i+1,n):
            s = s + m[i,j]*x[j,0]
            x[i,0] = (r[i,0] - s)/m[i,i]
    
    return x

In [4]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9
# 2*x1 + 1*x2 - 1*x3 =  3
# 3*x1 - 1*x2 - 2*x3 = -4

# Sistema escalonado:
#
# 1*x1 + 2*x2 + 1*x3 =  9
#        1*x2 + 1*x3 =  5
#               2*x3 =  4

M = np.matrix([[1,2,1],[0,1,1],[0,0,2]])
R = np.matrix([[9],[5],[4]])
X = solucao(M,R,3)
print(X)

[[ 1.]
 [ 3.]
 [ 2.]]


ALGORITMO II: RESOLUÇÃO DE Ax = B ATRAVÉS DO MÉTODO DA ELIMINAÇÃO DE GAUSS

In [5]:
# Dado um sistema S, representado por uma matriz M de ordem N e por uma matriz resultado R de ordem Nx1, o algoritmo
# abaixo pega essas matrizes e retorna a matriz triangular equivalente a M e sua matriz resultado correspondente

def escalonamento(m,r,n):
    for i in range(n-1):
        for j in range(i+1,n):
            z = m[j,i]/m[i,i]
            m[j,i] = 0
            
            for k in range(i+1,n):
                m[j,k] = m[j,k] - z*m[i,k]
                r[j,0] = r[j,0] - z*r[i,0]

In [7]:
# Sistema de exemplo:
#
# 1*x1 + 2*x2 + 1*x3 =  9
# 2*x1 + 1*x2 - 1*x3 =  3
# 3*x1 - 1*x2 - 2*x3 = -4

O = np.matrix([[1,2,1],[0,1,1],[0,0,2]])
P = np.matrix([[9],[5],[4]])

escalonamento(O,P,3)
print("\n", O)
print("\n", P)


 [[1 2 1]
 [0 1 1]
 [0 0 2]]

 [[9]
 [5]
 [4]]


In [8]:
# Determina o resultado

X = solucao(M,R,3)
print("\n", X)


 [[ 1.]
 [ 3.]
 [ 2.]]
