In [1]:
"""
    O programa abaixo utiliza as seguintes regras para nomear variáveis:

    S = número de sequências de três números geradas
    M = Matriz Sx3 que armazena as sequências geradas

    LI: limite inferior para um intervalo de números aleatórios
    LS: limite superior para um intervalo de números aleatórios
"""

import numpy as np
from random import randint #gera números de ponto flutuante aleatórios num intervalo dado

In [10]:
"""
	Retorna uma matriz M_(Sx3) com sequências de números aleatórios entre LI e LS
"""

def sequencia(S,LI,LS):
	matriz = np.zeros((S,3))

	for i in range(0,S):
		for j in range(0,3):
			matriz[i,j] = randint(LI,LS)

	return matriz

S = 5
LI = -10
LS = 10

matrizDeSequencias = sequencia(S,LI,LS)
print(matrizDeSequencias)

[[  2. -10.  -4.]
 [  1.   9.  -2.]
 [-10.  -9.  10.]
 [ -1.   4.  -2.]
 [ -7.   8.  -4.]]


In [11]:
"""
	Dada uma matriz M_(Sx3) calcula o resultado da substituição dos elementos das sequências S nas equações abaixo:
	
	3*x1 + 2*x2 + 4*x3 = 1
	1*x1 + 1*x2 + 2*x3 = 2
	4*x1 + 3*x2 - 2*x3 = 3

	Os resultados são armazenados em outras matriz Sx3
"""

def resultado(M,S):
	matriz = np.zeros((S,3))
	
	for i in range(0,S):
		x1 = M[i,0] # pega o 1º valor da sequência i e armazena em x1
		x2 = M[i,1] # pega o 2º valor da sequência i e armazena em x2
		x3 = M[i,2] # pega o 3º valor da sequência i e armazena em x3

		eq1 = 3*x1 + 2*x2 + 4*x3 # obtém um resultado para a equação 1 a patir de x1, x2 e x3
		eq2 = 1*x1 + 1*x2 + 2*x3 # obtém um resultado para a equação 2 a patir de x1, x2 e x3
		eq3 = 4*x1 + 3*x2 - 2*x3 # obtém um resultado para a equação 3 a patir de x1, x2 e x3

		matriz[i,0] = eq1 # armazena o resultado da equação 1 na 1º posição dos resultados refeentes a sequênca i
		matriz[i,1] = eq2 # armazena o resultado da equação 1 na 1º posição dos resultados refeentes a sequênca i
		matriz[i,2] = eq3 # armazena o resultado da equação 1 na 1º posição dos resultados refeentes a sequênca i
	
	return matriz

S = 5

matrizDeResultados = resultado(matrizDeSequencias, S)
print(matrizDeResultados)

[[-30. -16. -14.]
 [ 13.   6.  35.]
 [ -8.   1. -87.]
 [ -3.  -1.  12.]
 [-21.  -7.   4.]]


In [17]:
"""
	Considerando a matriz M_(Sx3) de resultados, calcula o percentual de aproximação dos resultados obtidos com os resultados
	reais das equações

	3*x1 + 2*x2 + 4*x3 = 1
	1*x1 + 1*x2 + 2*x3 = 2
	4*x1 + 3*x2 - 2*x3 = 3

	As aproximações obtidas são armazenadas em outra matriz Sx3
"""

def aproximacao(M,S):
	matriz = np.zeros((S,3))

	rEq1 = 1 # resultado real da equação 1
	rEq2 = 2 # resultado real da equação 2
	rEq3 = 3 # resultado real da equação 3

	for i in range(0,S):
		oEq1 = M[i,0] # resultado obtido na equação 1 pela sequência i
		oEq2 = M[i,1] # resultado obtido na equação 2 pela sequência i
		oEq3 = M[i,2] # resultado obtifo na equação 3 pela sequência i

		apx1 = abs((rEq1-oEq1)/rEq1)*100 # aproximação da equação 1 para a sequência i
		apx2 = abs((rEq2-oEq2)/rEq2)*100 # aproximação da equação 2 para a sequência i
		apx3 = abs((rEq3-oEq3)/rEq3)*100 # aproximação da equação 3 para a sequência i

		matriz[i,0] = apx1 # armazena a aproximação da equação 1 para a sequência i
		matriz[i,1] = apx2 # armazena a aproximação da equação 2 para a sequência i
		matriz[i,2] = apx3 # armazena a aproximação da equação 3 para a sequência i
	
	return matriz

S = 5

matrizDeAproximacoes = aproximacao(matrizDeResultados, S)
print(matrizDeAproximacoes)

[[ 3100.           900.           566.66666667]
 [ 1200.           200.          1066.66666667]
 [  900.            50.          3000.        ]
 [  400.           150.           300.        ]
 [ 2200.           450.            33.33333333]]


In [19]:
"""
	Considerando uma matriz Sx3 de aproximações, calcula a média dessas aproximações e armazena numa matriz Sx1
"""

def media(M,S):
	matriz = np.zeros((S,1))

	for i in range(0,S):
		aEq1 = M[i,0] # percentual de aproximação da equação 1 para a sequência i
		aEq2 = M[i,1] # percentual de aproximação da equação 2 para a sequência i
		aEq3 = M[i,2] # percentual de aproximação da equação 3 para a sequência i
		
		mSis = (aEq1 + aEq2 + aEq3)/3 # percentual médio de aproximação do sistema para a sequência i

		matriz[i,0] = mSis # armazena a média geral de aproximação do resultado da sequência i

	return matriz

S = 5

matrizDeMedia = media(matrizDeAproximacoes, S)
print(matrizDeMedia)

[[ 1522.22222222]
 [  822.22222222]
 [ 1316.66666667]
 [  283.33333333]
 [  894.44444444]]


In [20]:
"""
	O algoritmo de ordenação abaixo irá receber uma matriz de média de aproximações Sx1 (Ma) e a matriz de sequências Sx3
	correspondente (Ms). Essas matrizes serão ordenadas em ordem crescente.
"""

def bubbleSort(Ma, Ms, S):
	ordenado = False
	mApx = np.zeros((S,1)) # recebe uma cópia da matriz de médias das aproximações
	mSeq = np.zeros((S,3)) # recebe uma cópia da matriz de sequências

	# Copia a matriz de aproximações
	for i in range(0,S):
		mApx[i,0] = Ma[i,0]
	
	# Copia a matriz de sequências
	for i in range(0,S):
		for j in range(0,3):
			mSeq[i,j] = Ms[i,j]

	# Ordena as matrizes
	while not ordenado:
		ordenado = True
		
		for i in range(0,S-1):
			if mApx[i,0] > mApx[i+1,0]:
				
				# Ordena os dados da matriz de médias de aproximação
				mApx[i,0], mApx[i+1,0] = mApx[i+1,0], mApx[i,0]

				# Ordena os dados da matriz de sequências
				mSeq[i,0], mSeq[i+1,0] = mSeq[i+1,0], mSeq[i,0] # coluna 0: representa os valores de x1 para a sequência i
				mSeq[i,1], mSeq[i+1,1] = mSeq[i+1,1], mSeq[i,1] # coluna 1: representa os valores de x2 para a sequência i
				mSeq[i,2], mSeq[i+1,2] = mSeq[i+1,2], mSeq[i,2] # coluna 2: representa os valores de x3 para a sequência i

				ordenado = False
	
	return mApx, mSeq

mediaOrdenada = bubbleSort(matrizDeMedia, matrizDeSequencias, S)[0]
sequenciaOrdenada = bubbleSort(matrizDeAproximacoes, matrizDeSequencias, S)[1]

print(mediaOrdenada)
print(sequenciaOrdenada)

[[  283.33333333]
 [  822.22222222]
 [  894.44444444]
 [ 1316.66666667]
 [ 1522.22222222]]
[[ -1.   4.  -2.]
 [-10.  -9.  10.]
 [  1.   9.  -2.]
 [ -7.   8.  -4.]
 [  2. -10.  -4.]]
